import { Ranking, RankingItem } from '../model/rankings-item';

export const mockRankings: RankingItem[] = [
  {
    playerId: '1dds1',
    displayName: 'tuandc',
    score: 123,
    profileImage: '',
    ranking: Ranking.PLATINUM_II,
    level: 12,
  },
  {
    playerId: 'eeff2c',
    displayName: 'mnhdb',
    score: 100,
    profileImage: '',
    ranking: Ranking.PLATINUM_III,
    level: 12,
  },
  {
    playerId: 'sdf',
    displayName: 'minhht',
    score: 79,
    profileImage: '',
    ranking: Ranking.GOLD_I,
    level: 12,
  },
  {
    playerId: '2ydt',
    displayName: 'kietvt',
    score: 58,
    profileImage: '',
    ranking: Ranking.GOLD_III,
    level: 12,
  },
  {
    playerId: 'ewfwe1',
    displayName: 'dungtd',
    score: 12,
    profileImage: '',
    ranking: Ranking.BRONZE_II,
    level: 12,
  },
  {
    playerId: '1dds1',
    displayName: 'tuandc',
    score: 123,
    profileImage: '',
    ranking: Ranking.PLATINUM_II,
    level: 12,
  },
  {
    playerId: 'eeff2c',
    displayName: 'mnhdb',
    score: 100,
    profileImage: '',
    ranking: Ranking.PLATINUM_III,
    level: 12,
  },
  {
    playerId: 'sdf',
    displayName: 'minhht',
    score: 79,
    profileImage: '',
    ranking: Ranking.GOLD_I,
    level: 12,
  },
  {
    playerId: '2ydt',
    displayName: 'kietvt',
    score: 58,
    profileImage: '',
    ranking: Ranking.GOLD_III,
    level: 12,
  },
  {
    playerId: 'ewfwe1',
    displayName: 'dungtd',
    score: 12,
    profileImage: '',
    ranking: Ranking.BRONZE_II,
    level: 12,
  },
  {
    playerId: '1dds1',
    displayName: 'tuandc',
    score: 123,
    profileImage: '',
    ranking: Ranking.PLATINUM_II,
    level: 12,
  },
  {
    playerId: 'eeff2c',
    displayName: 'mnhdb',
    score: 100,
    profileImage: '',
    ranking: Ranking.PLATINUM_III,
    level: 12,
  },
  {
    playerId: 'sdf',
    displayName: 'minhht',
    score: 79,
    profileImage: '',
    ranking: Ranking.GOLD_I,
    level: 12,
  },
  {
    playerId: '2ydt',
    displayName: 'kietvt',
    score: 58,
    profileImage: '',
    ranking: Ranking.GOLD_III,
    level: 12,
  },
  {
    playerId: 'ewfwe1',
    displayName: 'dungtd',
    score: 12,
    profileImage: '',
    ranking: Ranking.BRONZE_II,
    level: 12,
  },
];
